CXX      = g++
HIPCC    = /opt/rocm/bin/hipcc
OUT_SERVER = app_server
OUT_CLIENT = app_client

# AMD ROCm Paths (Linux)
AMD_INC  = -I/opt/rocm/include
AMD_LIB  = -L/opt/rocm/lib -lamdhip64

# Flags and Libraries (Linux SFML)
CXXFLAGS = -Wall -std=c++17 -fPIC -Iinclude -Isrc -I/usr/local/include $(AMD_INC)
HIPFLAGS = -g -fPIC
LIBS     = -L/usr/local/lib -Wl,-rpath=/usr/local/lib -lsfml-graphics -lsfml-window -lsfml-system -lsfml-network $(AMD_LIB)

# ==========================================
# BLOCK 1: C++ / CPU (Core Sources)
# ==========================================
CORE_SOURCES = src/swarm/swarm_manager.cpp \
          src/swarm/spawn_logic/matrix_group.cpp \
          src/swarm/spawn_logic/mission_orchestrator.cpp \
          src/SimulationEngine.cpp \
          src/utils/math_utils.cpp \
          src/world/world.cpp \
          src/rendering/renderer.cpp \
          src/rendering/camera.cpp \
          src/AI/drone_ai.cpp \
          src/AI/states.cpp \
          src/AI/matrix_ai.cpp \
          src/network/bridge.cpp \
          src/world/procedural_city.cpp \
          src/lab.cpp

# ==========================================
# BLOCK 2: HIP / GPU (Kernels)
# ==========================================
HIP_SRC = src/swarm/swarm_dynamics.hip
HIP_OBJ = build/swarm_dynamics.o

HEADERS = include/global_config.h \
          include/swarm/swarm_dynamics.h \
          include/swarm/swarm_manager.h \
          include/AI/states.h \
          include/AI/drone_ai.h \
          include/AI/matrix_ai.h

# ==========================================
# BUILD RULES
# ==========================================
all: server

server: build_dir $(HIP_OBJ)
	@echo "[BUILD] Compiling Server on Linux Cloud..."
	$(CXX) $(CXXFLAGS) src/main_server.cpp $(CORE_SOURCES) $(HIP_OBJ) -o $(OUT_SERVER) $(LIBS)

client: build_dir $(HIP_OBJ)
	@echo "[BUILD] Compiling Client on Linux Cloud..."
	$(CXX) $(CXXFLAGS) src/main_client.cpp $(CORE_SOURCES) $(HIP_OBJ) -o $(OUT_CLIENT) $(LIBS)

$(HIP_OBJ): $(HIP_SRC) $(HEADERS)
	@echo "[AMD] Compiling GPU Kernels..."
	$(HIPCC) $(HIPFLAGS) -fno-exceptions -fno-rtti -c $(HIP_SRC) -o $(HIP_OBJ) -Iinclude

build_dir:
	@mkdir -p build

clean:
	@rm -rf build
	@rm -f $(OUT_SERVER) $(OUT_CLIENT)
